package com.article.demo.bean;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Article implements Serializable {


    private Integer comcount;
    private List<Comment> ctexts;
    private String cids;
    private String uname;
    private String signature;
    private String sitename;
    private String typename;

    public Integer getComcount() {
        return comcount;
    }

    public void setComcount(Integer comcount) {
        this.comcount = comcount;
    }

    public String getTypename() {
        return typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public String getSitename() {
        return sitename;
    }

    public void setSitename(String sitename) {
        this.sitename = sitename;
    }

    public List<Comment> getCtexts() {
        return ctexts;
    }

    public void setCtexts(List<Comment> ctexts) {
        this.ctexts = ctexts;
    }

    public String getCids() {
        return cids;
    }

    public void setCids(String cids) {
        this.cids = cids;
    }

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.aid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.title
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.context
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.uid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.tid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.sid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.creattime
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date creattime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.Pageviews
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer pageviews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_article.praise
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer praise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.aid
     *
     * @return the value of c_article.aid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.aid
     *
     * @param aid the value for c_article.aid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.title
     *
     * @return the value of c_article.title
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.title
     *
     * @param title the value for c_article.title
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.context
     *
     * @return the value of c_article.context
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.context
     *
     * @param context the value for c_article.context
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.uid
     *
     * @return the value of c_article.uid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.uid
     *
     * @param uid the value for c_article.uid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.tid
     *
     * @return the value of c_article.tid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.tid
     *
     * @param tid the value for c_article.tid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.sid
     *
     * @return the value of c_article.sid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.sid
     *
     * @param sid the value for c_article.sid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.creattime
     *
     * @return the value of c_article.creattime
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.creattime
     *
     * @param creattime the value for c_article.creattime
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.Pageviews
     *
     * @return the value of c_article.Pageviews
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getPageviews() {
        return pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.Pageviews
     *
     * @param pageviews the value for c_article.Pageviews
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setPageviews(Integer pageviews) {
        this.pageviews = pageviews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_article.praise
     *
     * @return the value of c_article.praise
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_article.praise
     *
     * @param praise the value for c_article.praise
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", title=").append(title);
        sb.append(", context=").append(context);
        sb.append(", uid=").append(uid);
        sb.append(", tid=").append(tid);
        sb.append(", sid=").append(sid);
        sb.append(", creattime=").append(creattime);
        sb.append(", pageviews=").append(pageviews);
        sb.append(", praise=").append(praise);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}