package com.article.demo.bean;

import java.io.Serializable;

public class C_Site implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_site.sid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_site.sitename
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private String sitename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_site.sid
     *
     * @return the value of c_site.sid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_site.sid
     *
     * @param sid the value for c_site.sid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_site.sitename
     *
     * @return the value of c_site.sitename
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public String getSitename() {
        return sitename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_site.sitename
     *
     * @param sitename the value for c_site.sitename
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setSitename(String sitename) {
        this.sitename = sitename == null ? null : sitename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", sitename=").append(sitename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}