package com.article.demo.bean;

import java.io.Serializable;

public class C_Type implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_type.tid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_type.typename
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_type.tid
     *
     * @return the value of c_type.tid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_type.tid
     *
     * @param tid the value for c_type.tid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_type.typename
     *
     * @return the value of c_type.typename
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_type.typename
     *
     * @param typename the value for c_type.typename
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tid=").append(tid);
        sb.append(", typename=").append(typename);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}