package com.article.demo.bean;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Comment implements Serializable {

    private String uname;

    public String getUname() {
        return uname;
    }

    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_comment.cid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_comment.text
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_comment.uid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_comment.aid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_comment.commenttime
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date commenttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_comment
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_comment.cid
     *
     * @return the value of c_comment.cid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_comment.cid
     *
     * @param cid the value for c_comment.cid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_comment.text
     *
     * @return the value of c_comment.text
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_comment.text
     *
     * @param text the value for c_comment.text
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_comment.uid
     *
     * @return the value of c_comment.uid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_comment.uid
     *
     * @param uid the value for c_comment.uid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_comment.aid
     *
     * @return the value of c_comment.aid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_comment.aid
     *
     * @param aid the value for c_comment.aid
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_comment.commenttime
     *
     * @return the value of c_comment.commenttime
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_comment.commenttime
     *
     * @param commenttime the value for c_comment.commenttime
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public void setCommenttime(Date commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_comment
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", text=").append(text);
        sb.append(", uid=").append(uid);
        sb.append(", aid=").append(aid);
        sb.append(", commenttime=").append(commenttime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}