package com.article.demo.dao;

import com.article.demo.bean.Article;
import com.article.demo.bean.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    long countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    Article selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_article
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByPrimaryKey(Article record);

    void uodPageviews(Integer aid);
}