package com.article.demo.dao;

import com.article.demo.bean.C_Site;
import com.article.demo.bean.C_SiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface C_SiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    long countByExample(C_SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int deleteByExample(C_SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int insert(C_Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int insertSelective(C_Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    List<C_Site> selectByExample(C_SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    C_Site selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") C_Site record, @Param("example") C_SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByExample(@Param("record") C_Site record, @Param("example") C_SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByPrimaryKeySelective(C_Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_site
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByPrimaryKey(C_Site record);
}