package com.article.demo.dao;

import com.article.demo.bean.C_Type;
import com.article.demo.bean.C_TypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface C_TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    long countByExample(C_TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int deleteByExample(C_TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int insert(C_Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int insertSelective(C_Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    List<C_Type> selectByExample(C_TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    C_Type selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") C_Type record, @Param("example") C_TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByExample(@Param("record") C_Type record, @Param("example") C_TypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByPrimaryKeySelective(C_Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_type
     *
     * @mbg.generated Sat Jun 15 10:12:21 CST 2019
     */
    int updateByPrimaryKey(C_Type record);
}